name: Check build of CookieMonster
on: pull_request
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Check if CookieMonster.js is built correctly 
      run: |
        cat ./src/Header.js ./src/Cache.js ./src/Config.js ./src/Data.js ./src/Disp.js ./src/Main.js ./src/Sim.js ./src/Footer.js > CookieMonsterTest.js
        if cmp -s CookieMonster.js CookieMonsterTest.js; then
            echo '### SUCCESS: CookieMonster is correctly built! ###'
        else
            echo '### WARNING: CookieMonster.js does not seem to be correct. Have you compiled the source files into the final file using either of the combine files? ###'
            exit 1
        fi
