name: CI
on: pull_request
jobs:
  Check_ESLint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run ESLint
      run: |
        npm install
        npx eslint src
  Check_main_file:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Check if CookieMonster.js is built correctly 
      run: |
        npm install
        npx webpack
        npx terser ./dist/Header.js ./dist/Cache.js ./dist/Config.js ./dist/Data.js ./dist/Disp.js ./dist/Main.js ./dist/Sim.js ./dist/Footer.js -o CookieMonsterTest.js
        if cmp CookieMonster.js CookieMonsterTest.js; then
            echo '### SUCCESS: CookieMonster is correctly built! ###'
        else
            echo '### WARNING: CookieMonster.js does not seem to be correct. Make sure to run "npm run build" after saving all your changes! ###'
            exit 1
        fi
