name: CI
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '12'
    - name: Install dependencies
      run: 
        yarn init
        yarn add eslint --dev
        yarn install
    - name: Lint
      run: 
        yarn run eslint --init
        eslint .
