name: CI
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install modules
      run: |
        yarn
        yarn add eslint --dev
        yarn run eslint --init
    - name: Run ESLint
      run: eslint . --ext .js
