name: CI
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install modules
      run: yarn init
      run: yarn add eslint --dev
      run: yarn run eslint --init
    - name: Run ESLint
      run: eslint . --ext .js
