name: CI
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '12'
    - name: Install dependencies
      run: |
        npm init
        npm install eslint --save-dev
    - name: Lint
      run: |
        npx eslint --init
        npx eslint . --ext .js
